# Site settings
title: Ricardo Sánchez Sotres
email: odrakir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  UX Developer, Consultant & iOS Programmer
  from Madrid to the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://odrakir.github.io" # the base hostname & protocol for your site
twitter_username: foolonhill
github_username:  Odrakir

# Build settings
markdown: kramdown
